/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kevin.androidffmpegplayer;

public class FFmpegDecoder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FFmpegDecoder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FFmpegDecoder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        KxFFmpegJNI.delete_FFmpegDecoder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void startDecoder() {
    KxFFmpegJNI.FFmpegDecoder_startDecoder(swigCPtr, this);
  }

  public boolean isStart() {
    return KxFFmpegJNI.FFmpegDecoder_isStart(swigCPtr, this);
  }

  public boolean writePacket(byte[] data) {
    return KxFFmpegJNI.FFmpegDecoder_writePacket(swigCPtr, this, data);
  }

  public void readFrame() {
    KxFFmpegJNI.FFmpegDecoder_readFrame(swigCPtr, this);
  }

  public void stopDecoder() {
    KxFFmpegJNI.FFmpegDecoder_stopDecoder(swigCPtr, this);
  }

  public void setWindow(java.lang.Object surface) {
    KxFFmpegJNI.FFmpegDecoder_setWindow(swigCPtr, this, surface);
  }

  public FFmpegDecoder() {
    this(KxFFmpegJNI.new_FFmpegDecoder(), true);
  }

}
