/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kevin.androidffmpegplayer;

public class KxFFmpegJNI {

  static {
      try {
          System.loadLibrary("kxffmpeg");
      } catch (UnsatisfiedLinkError e) {
          System.err.println("libkxffmpeg.so failed to load. \n" + e);
          System.exit(1);
      }
  }

  public final static native void FFmpegDecoder_startDecoder(long jarg1, FFmpegDecoder jarg1_);
  public final static native boolean FFmpegDecoder_isStart(long jarg1, FFmpegDecoder jarg1_);
  public final static native boolean FFmpegDecoder_writePacket(long jarg1, FFmpegDecoder jarg1_, byte[] jarg2);
  public final static native void FFmpegDecoder_readFrame(long jarg1, FFmpegDecoder jarg1_);
  public final static native void FFmpegDecoder_stopDecoder(long jarg1, FFmpegDecoder jarg1_);
  public final static native void FFmpegDecoder_setWindow(long jarg1, FFmpegDecoder jarg1_, java.lang.Object jarg2);
  public final static native long new_FFmpegDecoder();
  public final static native void delete_FFmpegDecoder(long jarg1);
}
